### ISSUE TITLE
 in development some images can be show in my project but when i use npm run build:win  these images can't show

### ISSUE THREAD

**Issue by zzxdt** [jooy2/vutron#186] opened 2024-04-25 05:04 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Device information (please complete the following information):**
 - OS Name: [e.g. Windows, macOS, Linux...]
 - OS Version: [e.g. 11, 10.14...]

**Screenshots & Attachments**

**Additional context**

**Comment by jooy2** [comment] 2024-05-02 10:01
duplicate of #187 , invalid issue. closed.

**Closed by jooy2** 2024-05-02 10:01 UTC
Labels: bug
